spring.application.name=auth-service
server.port=8082

# DB (docker hostname)
spring.datasource.url=jdbc:postgresql://postgres:5432/templedb
spring.datasource.username=temple
spring.datasource.password=temple
spring.jpa.hibernate.ddl-auto=update

# JWT secret (for learning). Later we can switch to RSA keys.
app.jwt.secret=change-this-to-a-long-random-string-please
app.jwt.issuer=temple-auth
app.jwt.expMinutes=120

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,email,profile

# After Google login, redirect back to UI with JWT
app.oauth2.redirectUri=http://localhost:3000/oauth2/callback

# Tell Spring it's behind a proxy (Gateway)
server.forward-headers-strategy=framework

# Force correct external base URL
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}


